<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!--Avalonia doesen't support TrimMode=link currently,but we are working on that https://github.com/AvaloniaUI/Avalonia/issues/6892 -->
    <TrimMode>copyused</TrimMode>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <PackageOutputPath>./nupkg</PackageOutputPath>

    <Authors>Demortier Jeremy</Authors>
    <Description>Double dimension hierarchy grid</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Skia" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" />
    <PackageReference Include="ReactiveMarbles.ObservableEvents.SourceGenerator" PrivateAssets="all" />
    <PackageReference Include="ReactiveUI.Avalonia" />
    <PackageReference Include="SkiaSharp.Views" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HierarchyGrid.Skia\HierarchyGrid.Skia.csproj" />
  </ItemGroup>

</Project>
