---
# See https://gitlab.com/tobiaskoch/gitlab-ci-example-dotnetcore-windows

.shared_windows_runners:
  tags:
    - shared-windows
    - windows
    - windows-1809

# image: microsoft/dotnet:latest
image: mcr.microsoft.com/dotnet/core/sdk:3.1

### Define variables
variables :
  OBJECTS_DIRECTORY: 'obj'
  NUGET_PACKAGES_DIRECTORY: '.nuget'
  SOURCE_CODE_PATH: '*/*/'

### Define stage list
stages:
  - build

build:
  only:
    - master
  artifacts:
      paths:
          - HierarchyGrid.Definitions/nupkg/*.nupkg
          - VirtualHierarchyGrid/nupkg/*.nupkg
  stage: build
  extends:
    - .shared_windows_runners
  script:
    - 'dotnet restore'
    - 'dotnet build'
    - 'dotnet pack'

