<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

	<PropertyGroup>
		<PackageOutputPath>./nupkg</PackageOutputPath>

		<Authors>Demortier Jeremy</Authors>
		<Description>HierarchyGrid rendering in Skia</Description>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="SkiaSharp.HarfBuzz" />
    <PackageReference Include="SkiaSharp.NativeAssets.Linux" />
    <PackageReference Include="SkiaSharp.NativeAssets.macOS" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" />
    <PackageReference Include="Svg.Skia" />
    <PackageReference Include="Topten.RichTextKit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HierarchyGrid.Definitions\HierarchyGrid.Definitions.csproj" />
  </ItemGroup>

</Project>
