<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>default</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Resources\comment.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Resources\edit.svg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" />
    <PackageReference Include="NLog" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HierarchyGrid\HierarchyGrid.csproj" />
  </ItemGroup>
</Project>