<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
    <PackageOutputPath>./nupkg</PackageOutputPath>

    <Authors>Demortier Jeremy</Authors>
    <Description>Definitions used by HierarchyGrid</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="nupkg\**" />
    <EmbeddedResource Remove="nupkg\**" />
    <None Remove="nupkg\**" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>HierarchyGrid</_Parameter1>
    </AssemblyAttribute>

    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>HierarchyGrid.Avalonia</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LanguageExt.Core" Version="4.4.9" />
    <PackageReference Include="morelinq" Version="4.4.0" />
    <PackageReference Include="ReactiveUI" Version="20.4.1" />
    <PackageReference Include="ReactiveUI.SourceGenerators" Version="2.4.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Text.Json" Version="9.0.8" />
  </ItemGroup>
</Project>