<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows10.0.19041</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<PropertyGroup>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>

	<PropertyGroup>
		<PackageOutputPath>./nupkg</PackageOutputPath>

		<Authors>Demortier Jeremy</Authors>
		<Description>Double dimension hierarchy grid</Description>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ReactiveMarbles.ObservableEvents.SourceGenerator">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="ReactiveUI.WPF" />
		<PackageReference Include="SkiaSharp.HarfBuzz" />
		<PackageReference Include="SkiaSharp.Views.WPF" />
		<PackageReference Include="TextCopy" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\HierarchyGrid.Definitions\HierarchyGrid.Definitions.csproj" />
		<ProjectReference Include="..\HierarchyGrid.Skia\HierarchyGrid.Skia.csproj" />
	</ItemGroup>
</Project>
