<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>false</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Avalonia" Version="12.1.1" />
    <PackageVersion Include="Avalonia.Desktop" Version="12.1.1" />
    <PackageVersion Include="Avalonia.Diagnostics" Version="11.3.20" />
    <PackageVersion Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <PackageVersion Include="Avalonia.Skia" Version="12.1.1" />
    <PackageVersion Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageVersion Include="Bogus" Version="35.6.5" />
    <PackageVersion Include="FluentAssertions" Version="8.10.0" />
    <PackageVersion Include="LanguageExt.Core" Version="4.4.9" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageVersion Include="morelinq" Version="4.4.0" />
    <PackageVersion Include="NLog" Version="6.2.0" />
    <PackageVersion Include="ReactiveMarbles.ObservableEvents.SourceGenerator" Version="1.3.1" />
    <PackageVersion Include="ReactiveUI" Version="24.1.0" />
    <PackageVersion Include="ReactiveUI.Avalonia" Version="12.1.1" />
    <PackageVersion Include="ReactiveUI.SourceGenerators" Version="3.2.0" />
    <PackageVersion Include="ReactiveUI.Testing" Version="24.1.0" />
    <PackageVersion Include="ReactiveUI.WPF" Version="24.1.0" />
    <PackageVersion Include="SkiaSharp" Version="4.151.1" />
    <PackageVersion Include="SkiaSharp.HarfBuzz" Version="4.151.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Linux" Version="4.151.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.macOS" Version="4.151.1" />
    <PackageVersion Include="SkiaSharp.NativeAssets.Win32" Version="4.151.1" />
    <PackageVersion Include="SkiaSharp.Views" Version="4.151.1" />
    <PackageVersion Include="SkiaSharp.Views.WPF" Version="4.151.1" />
    <PackageVersion Include="Splat.DependencyInjection.SourceGenerator" Version="2.3.0" />
    <PackageVersion Include="Svg.Skia" Version="5.2.1" />
    <PackageVersion Include="System.Text.Json" Version="10.0.3" />
    <PackageVersion Include="TextCopy" Version="6.2.1" />
    <PackageVersion Include="Topten.RichTextKit" Version="0.4.167" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="4.0.0" />
  </ItemGroup>
</Project>