name: VirtualHierarchyGrid integration

on:
  push:
    tags:
      - 0.*
      - 2.*
env:
  configuration: Release

jobs:

  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: NuGet restore
        run: dotnet restore
        working-directory: src

      - name: Build
        run: dotnet build --configuration=Release --verbosity=minimal --no-restore
        working-directory: src

      - name: Unit tests
        run: dotnet test --configuration=Release --verbosity=minimal --no-restore
        working-directory: src

      - uses: olegtarasov/get-tag@v2.1.2
        id: tagName

      - name: Pack
        run: dotnet pack -p:PackageVersion=${{ steps.tagName.outputs.tag }} --configuration=Release --verbosity=minimal --no-restore
        working-directory: src

      - name: Push to nuget
        run: dotnet nuget push **/HierarchyGrid.Definitions/nupkg/*.nupkg -k ${{ secrets.Nuget_Key }} -s https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Push to nuget
        run: dotnet nuget push **/HierarchyGrid.Skia/nupkg/*.nupkg -k ${{ secrets.Nuget_Key }} -s https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Push to nuget
        run: dotnet nuget push **/HierarchyGrid/nupkg/*.nupkg -k ${{ secrets.Nuget_Key }} -s https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Push to nuget
        run: dotnet nuget push **/HierarchyGrid.Avalonia/nupkg/*.nupkg -k ${{ secrets.Nuget_Key }} -s https://api.nuget.org/v3/index.json --skip-duplicate

