name: VirtualHierarchyGrid integration

on:
  push:
    tags:
      - 0.*
      - 1.*
env:
  configuration: Release

jobs:

  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v1.8.0
        with:
          dotnet-version: 6.0.x

      - name: NuGet restore
        run: dotnet restore
        working-directory: src

      - name: Build
        run: dotnet build --configuration=Release --verbosity=minimal --no-restore
        working-directory: src

      - name: Unit tests
        run: dotnet test --configuration=Release --verbosity=minimal --no-restore
        working-directory: src

      - uses: little-core-labs/get-git-tag@v3.0.1
        id: tagName

      - name: Pack
        run: dotnet pack -p:PackageVersion=${{ steps.tagName.outputs.tag }} --configuration=Release --verbosity=minimal --no-restore
        working-directory: src

      - name: Push to nuget
        run: dotnet nuget push **/HierarchyGrid.Definitions/nupkg/*.nupkg -k ${{ secrets.Nuget_Key }} -s https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Push to nuget
        run: dotnet nuget push **/HierarchyGrid.Skia/nupkg/*.nupkg -k ${{ secrets.Nuget_Key }} -s https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Push to nuget
        run: dotnet nuget push **/HierarchyGrid/nupkg/*.nupkg -k ${{ secrets.Nuget_Key }} -s https://api.nuget.org/v3/index.json --skip-duplicate
    
