name: VirtualHierarchyGrid integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
env:
  configuration: Release

jobs:

  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: NuGet restore
        run: dotnet restore
        working-directory: src

      - name: Build
        run: dotnet build --configuration=Release --verbosity=minimal --no-restore
        working-directory: src

      - name: Unit tests
        run: dotnet test --configuration=Release --verbosity=minimal --no-restore
        working-directory: src